name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published

jobs:
  build-forgejo:
    if: github.server_url != 'https://github.com'
    uses: l3tum/reusable-workflows/.github/workflows/publish-forgejo.yml@main
    runs-on: ubuntu-latest
    with:
      PUSH: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    secrets:
      PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
